### ISSUE TITLE
Error for battery on Thinkpad X220 (External battery only)

### ISSUE THREAD

**Issue by nobodywasishere** [devksingh4/thinkpad-tools#6] opened 2019-04-29 19:12 UTC
![DeepinScreenshot_select-area_20190429105938](https://user-images.githubusercontent.com/32797552/56920426-2714fd80-6a91-11e9-85ed-65800215dfb2.png)

This error occurs for anything dealing with battery on Thinkpad x220 (only has an external battery)

**Comment by devksingh4** [comment] 2019-05-01 13:09
Hmmmm...
It seems to me that the program isn't try/excepting when seeing how many batteries there are. 

I am a little busy right now with school so I'll get to it when I can

**Comment by devksingh4** [comment] 2019-10-08 22:29
So I finally got the chance to test this on another computer with only one battery (T460). It seems to work as expected. Not sure what's going on but I'll make sure to take a look at this after I finish undervolting support

**Comment by devksingh4** [comment] 2019-10-16 05:40
Yeah after testing this with another computer, I dont see this issue. If you would like to me to take a look, please try the new version and let me know if the issue is still there. Otherwise, I will close the issue

**Comment by devksingh4** [comment] 2019-10-19 02:08
No update, so closing issue

**Closed as completed by devksingh4** 2019-10-19 02:08 UTC
Labels: bug, good first issue, question

**Comment by nobodywasishere** [comment] 2019-10-19 02:47
Hello. I apologize for not getting back sooner. I do not use this computer regularly anymore (I switched to a T450) but after git cloning and sudo installing the newest from git, the problem still persists on this machine, i'm not sure why. If there's anything as far as terminal commands/system configs you want to know, I'd be more than happy to give them. The error I'm getting right now, which may be the same as before:
```
$ thinkpad-tools battery list
Traceback (most recent call last):
  File "/usr/bin/thinkpad-tools", line 4, in <module>
    __import__('pkg_resources').run_script('thinkpad-tools===0.9.2-hotfix1', 'thinkpad-tools')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.7/site-packages/thinkpad_tools-0.9.2_hotfix1-py3.7.egg/EGG-INFO/scripts/thinkpad-tools", line 12, in <module>
  File "/usr/lib/python3.7/site-packages/thinkpad_tools-0.9.2_hotfix1-py3.7.egg/assets/cmd.py", line 63, in commandline_parser
    """
  File "/usr/lib/python3.7/site-packages/thinkpad_tools-0.9.2_hotfix1-py3.7.egg/assets/battery.py", line 276, in run
  File "/usr/lib/python3.7/site-packages/thinkpad_tools-0.9.2_hotfix1-py3.7.egg/assets/battery.py", line 128, in read_values
ZeroDivisionError: division by zero

```

If it helps at all here's this
```
$ neofetch
██████████████████  ████████   michael@michael-x220 
██████████████████  ████████   -------------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: 42875TU ThinkPad X220 
████████            ████████   Kernel: 4.19.69-1-MANJARO 
████████  ████████  ████████   Uptime: 9 mins 
████████  ████████  ████████   Packages: 1209 (pacman) 
████████  ████████  ████████   Shell: bash 5.0.11 
████████  ████████  ████████   Resolution: 1366x768 
████████  ████████  ████████   DE: Xfce 
████████  ████████  ████████   WM: Xfwm4 
████████  ████████  ████████   WM Theme: Adapta-Maia 
████████  ████████  ████████   Theme: Matcha-dark-sea [GTK2], Adw 
████████  ████████  ████████   Icons: Papirus-Maia [GTK2], Adwait 
                               Terminal: xfce4-terminal 
                               Terminal Font: Monospace 12 
                               CPU: Intel i5-2450M (4) @ 3.100GHz 
                               GPU: Intel 2nd Generation Core Pro 
                               Memory: 1659MiB / 3826MiB 

                                                       

```

**Comment by devksingh4** [comment] 2019-10-19 14:42
It seems that there is a bigger issue with the whole Battery part of the tool. I will investigate further when I get a chance.
